spring:
  main:
    allow-circular-references: true
  profiles:
    active: test
---

spring:
  main:
    allow-circular-references: true
  profiles:
    active: loadInitialData
  datasource:
    url: "jdbc:h2:mem:testdb"
    driver-class-name: "org.h2.Driver"
    username: "sa"
    password: "password"
  h2:
    console:
      enabled: true
  mail:
    host: "smtp.office365.com"
    port: 587
    username: "springspringtest@outlook.com"
    password: "syUSv9hU2QCZjqK"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true